### ISSUE TITLE
No result after file is dropped

### ISSUE THREAD

**Issue by pierrealauzet** [ewenme/tracklister#2]
Hello friends,

I first noticed that this website I was using was down for a few days: https://apps.ewen.io/traklister/

Then I went to this one: https://tracklister.club/
But I when a drop any NLM, nothing happens. Anyone else having those issues?

Cheers,
Pierre

**Comment by ewenme** [comment]
hi! let me know if you are still having this problem, I've done some work on the app since this time. I'll close for now.

**Comment by pierrealauzet** [comment]
I confirm this is working now, thank you Ewen for the amazing work here!!
